[package]
name = "torch-model-derivation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tch = "0.8.0"
tensorboard-rs = "0.5.9"
rayon = "1.5.3"
csv = "1.1.6"
noise = "0.8.2"
rand = "0.8.5"